name = "presstotalk-api"
main = "src/index.ts"
compatibility_date = "2023-01-29"

kv_namespaces = [
    { binding = "PRESSTOTALK", id = "82fcdc6cbea344ecb9e9e9ea1e0082ca", preview_id = "d5bc770724ca4ff7b9ca6dfea0015c72" }
]

[vars]
# The necessary secrets are:
# - AZURE_CLIENT_ID
